// <auto-generated>
// Generated by Dreamy Audio. Do not edit manually.
// </auto-generated>

namespace Dreamy.Audio.Generated
{
    public static class AudioLibraryIds
    {
        public static class Sounds
        {
            public const string UiClick1 = "core/ui.click1";
            public const string UiClick = "core/ui.click";
        }
        public static class Music
        {
            public const string MusicMain = "core/music.main";
        }
    }
}
